# Generated by Django 5.2.4 on 2025-07-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_lesson_options_lesson_order_lesson_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="key_topics",
            field=models.TextField(
                blank=True,
                help_text="List key topics, ideally one per line for simple display.",
                null=True,
            ),
        ),
    ]
